style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/<%= projectOwner %>/<%= projectRepository %>
options:
  commits:
    filters:
      Type:
        - build
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - style
        - test
        - chore
  commit_groups:
    title_maps:
      build: Build
      ci: CI/CD
      docs: Documentation
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      style: Source Code Style
      test: Test
      chore: Maintenance
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
